/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import controllers.ControlInscripcion;
import java.awt.Dimension;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import models.GestorDeInscripcion;
import models.dtos.TallerDTO;
import models.entitys.Taller;

/**
 *
 * @author sonic
 * Vista para mostrar la lista de talleres disponibles y permitir su seleccion.
 */
public class PantallaListaTalleres extends javax.swing.JFrame {

    private ControlInscripcion control;
    private TallerDTO tallerSeleccionado;

    /**
     * Creates new form PantallaListaTalleres
     */
    public PantallaListaTalleres(ControlInscripcion control) {
        this.control = control;
        initComponents();
        this.setTitle("Inscripción de Talleres ISW");
        this.setLocationRelativeTo(null); // Centra la ventana en la pantalla

        cargarTalleres();
        botonInscribir.setEnabled(false); // Deshabilita hasta seleccionar un taller
    }

    /**
     * Carga dinamicamente la lista de talleres desde el controloador y crea botones interactivos.
     * Cada botón muestra detalles al hacer clic en el, actualizando la seccion de detalles.
     * Usa BoxLayout vertical para una lista scrolleable.
     */
    private void cargarTalleres() {
        List<TallerDTO> talleres = control.obtenerTalleres();

        JPanel panelDeBotones = new JPanel();
        panelDeBotones.setLayout(new BoxLayout(panelDeBotones, BoxLayout.Y_AXIS));

        for (TallerDTO taller : talleres) {
            JButton botonTaller = new JButton(taller.getNombreTaller());
            botonTaller.setMaximumSize(new Dimension(Integer.MAX_VALUE, botonTaller.getMinimumSize().height)); // Para que ocupe todo el ancho

            botonTaller.addActionListener(e -> {
                mostrarDetallesTaller(taller);
            });

            panelDeBotones.add(botonTaller);
        }

        panelTalleres.setViewportView(panelDeBotones);
    }

     /**
     * Actualiza la seccion de detalles con la informacion del taller seleccionado.
     * Habilita el boton de inscribir y almacena la seleccion para el siguiente paso.
     * 
     * @param taller El taller seleccionado por el usuario.
     */
    private void mostrarDetallesTaller(TallerDTO taller) {
        this.tallerSeleccionado = taller;

        labelNombre.setText("Nombre del Taller: " + taller.getNombreTaller());
        labelInstructor.setText("Instructor: " + taller.getNombreInstructor());
        lblFechaInicio.setText("Fecha de inicio: " + taller.getFecha().toString());
        labelHorario.setText("Horario: " + taller.getHorario());
        txtField.setText(taller.getDescripcion());

        botonInscribir.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTalleres = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        panelDetalles = new javax.swing.JPanel();
        labelNombre = new javax.swing.JLabel();
        labelInstructor = new javax.swing.JLabel();
        lblFechaInicio = new javax.swing.JLabel();
        labelHorario = new javax.swing.JLabel();
        labelDescripcion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtField = new javax.swing.JTextArea();
        botonInscribir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelTalleres.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Inscribirse en un taller de la semana de ISW ");

        panelDetalles.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelNombre.setText("Nombre del Taller:");

        labelInstructor.setText("Instructor: ");

        lblFechaInicio.setText("Fecha de inicio: ");

        labelHorario.setText("Horario:");

        labelDescripcion.setText("Descripcion:");

        txtField.setColumns(20);
        txtField.setRows(5);
        jScrollPane1.setViewportView(txtField);

        javax.swing.GroupLayout panelDetallesLayout = new javax.swing.GroupLayout(panelDetalles);
        panelDetalles.setLayout(panelDetallesLayout);
        panelDetallesLayout.setHorizontalGroup(
            panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetallesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(panelDetallesLayout.createSequentialGroup()
                        .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNombre)
                            .addComponent(labelInstructor)
                            .addComponent(lblFechaInicio)
                            .addComponent(labelHorario)
                            .addComponent(labelDescripcion))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelDetallesLayout.setVerticalGroup(
            panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetallesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelInstructor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFechaInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelHorario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelDescripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        botonInscribir.setText("Inscribir");
        botonInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInscribirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(242, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelTalleres, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(panelDetalles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonInscribir, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(154, 154, 154))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTalleres, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelDetalles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonInscribir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInscribirActionPerformed
        // TODO add your handling code here:
        if (tallerSeleccionado != null) {
        PantallaInscripcionTaller pantallaInscripcion = new PantallaInscripcionTaller(this.control, this.tallerSeleccionado);
        control.setVistaInscripcion(pantallaInscripcion);
        pantallaInscripcion.setVisible(true);
        
    }
    }//GEN-LAST:event_botonInscribirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonInscribir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelDescripcion;
    private javax.swing.JLabel labelHorario;
    private javax.swing.JLabel labelInstructor;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel lblFechaInicio;
    private javax.swing.JPanel panelDetalles;
    private javax.swing.JScrollPane panelTalleres;
    private javax.swing.JTextArea txtField;
    // End of variables declaration//GEN-END:variables

}
